baseURL = 'https://albertllonch.github.io/'
languageCode = 'es'
title = "Odisea de Albert"
theme = "minimalist"
themesdir = "./themes"
defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false

[params]
  description = "Blog técnico personal sobre ingeniería de software, programación y tecnología."
  author = "Albert Llonch"
  email = "albertllonch@gmail.com"

[menu]
  [[menu.main]]
    name = "posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "tags"
    url = "/tags/"
    weight = 30

[taxonomies]
  tags = 'etiquetas'
  category = 'categorías'

[languages.es]
  title = "Odisea de Albert"
  languageCode = "es"
  languageName = "Español"
  contentDir = "content/es"
  weight = 1
  [languages.es.params]
    description = "Blog técnico personal sobre ingeniería de software, programación y tecnología."

# English configuration (secondary language)
[languages.en]
  title = "Albert Odyssey"
  languageCode = "en"
  languageName = "English"
  contentDir = "content/en"
  weight = 2
  [languages.en.params]
    description = "Personal technical blog about software engineering, programming, and technology."

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'github'
    lineNos = true
